// GENERATED by tool/gen_i18n.js from lib/core/constants/app_strings.dart.
// Do not edit by hand: run the generator instead.

part of 'app_text.dart';

/// The generated accessors, one per `AppStrings` member.
///
/// Typed getters rather than a bare map lookup at the call site: a mistyped
/// key is then a compile error, instead of a string that silently renders as
/// its own key.
mixin GeneratedText {
  /// Resolves [key] in the active language, falling back to English.
  String lookUp(String key);

  /// See `AppStrings.appName`.
  String get appName => lookUp('appName');

  /// See `AppStrings.appTagline`.
  String get appTagline => lookUp('appTagline');

  /// See `AppStrings.ok`.
  String get ok => lookUp('ok');

  /// See `AppStrings.cancel`.
  String get cancel => lookUp('cancel');

  /// See `AppStrings.yes`.
  String get yes => lookUp('yes');

  /// See `AppStrings.no`.
  String get no => lookUp('no');

  /// See `AppStrings.close`.
  String get close => lookUp('close');

  /// See `AppStrings.back`.
  String get back => lookUp('back');

  /// See `AppStrings.next`.
  String get next => lookUp('next');

  /// See `AppStrings.save`.
  String get save => lookUp('save');

  /// See `AppStrings.discard`.
  String get discard => lookUp('discard');

  /// See `AppStrings.delete`.
  String get delete => lookUp('delete');

  /// See `AppStrings.edit`.
  String get edit => lookUp('edit');

  /// See `AppStrings.retry`.
  String get retry => lookUp('retry');

  /// See `AppStrings.copy`.
  String get copy => lookUp('copy');

  /// See `AppStrings.copied`.
  String get copied => lookUp('copied');

  /// See `AppStrings.share`.
  String get share => lookUp('share');

  /// See `AppStrings.leave`.
  String get leave => lookUp('leave');

  /// See `AppStrings.done`.
  String get done => lookUp('done');

  /// See `AppStrings.skip`.
  String get skip => lookUp('skip');

  /// See `AppStrings.loading`.
  String get loading => lookUp('loading');

  /// See `AppStrings.pleaseWait`.
  String get pleaseWait => lookUp('pleaseWait');

  /// See `AppStrings.nothingHere`.
  String get nothingHere => lookUp('nothingHere');

  /// See `AppStrings.homeTitle`.
  String get homeTitle => lookUp('homeTitle');

  /// See `AppStrings.homeCreateRoom`.
  String get homeCreateRoom => lookUp('homeCreateRoom');

  /// See `AppStrings.homeJoinRoom`.
  String get homeJoinRoom => lookUp('homeJoinRoom');

  /// See `AppStrings.homePractice`.
  String get homePractice => lookUp('homePractice');

  /// See `AppStrings.homeLeaderboard`.
  String get homeLeaderboard => lookUp('homeLeaderboard');

  /// See `AppStrings.homeSettings`.
  String get homeSettings => lookUp('homeSettings');

  /// See `AppStrings.homeHowToPlay`.
  String get homeHowToPlay => lookUp('homeHowToPlay');

  /// See `AppStrings.homePlayingAs`.
  String get homePlayingAs => lookUp('homePlayingAs');

  /// See `AppStrings.homeChangeProfile`.
  String get homeChangeProfile => lookUp('homeChangeProfile');

  /// See `AppStrings.loginTitle`.
  String get loginTitle => lookUp('loginTitle');

  /// See `AppStrings.loginSubtitle`.
  String get loginSubtitle => lookUp('loginSubtitle');

  /// See `AppStrings.authEmailLabel`.
  String get authEmailLabel => lookUp('authEmailLabel');

  /// See `AppStrings.authEmailHint`.
  String get authEmailHint => lookUp('authEmailHint');

  /// See `AppStrings.authPasswordLabel`.
  String get authPasswordLabel => lookUp('authPasswordLabel');

  /// See `AppStrings.authPasswordHint`.
  String get authPasswordHint => lookUp('authPasswordHint');

  /// See `AppStrings.authPasswordNewHint`.
  String get authPasswordNewHint => lookUp('authPasswordNewHint');

  /// See `AppStrings.loginAction`.
  String get loginAction => lookUp('loginAction');

  /// See `AppStrings.loginCreateAccount`.
  String get loginCreateAccount => lookUp('loginCreateAccount');

  /// See `AppStrings.loginAsGuest`.
  String get loginAsGuest => lookUp('loginAsGuest');

  /// See `AppStrings.loginGuestNote`.
  String get loginGuestNote => lookUp('loginGuestNote');

  /// See `AppStrings.registerTitle`.
  String get registerTitle => lookUp('registerTitle');

  /// See `AppStrings.registerSubtitle`.
  String get registerSubtitle => lookUp('registerSubtitle');

  /// See `AppStrings.registerUpgradeSubtitle`.
  String get registerUpgradeSubtitle => lookUp('registerUpgradeSubtitle');

  /// See `AppStrings.registerAction`.
  String get registerAction => lookUp('registerAction');

  /// See `AppStrings.registerHaveAccount`.
  String get registerHaveAccount => lookUp('registerHaveAccount');

  /// See `AppStrings.authEmailRequired`.
  String get authEmailRequired => lookUp('authEmailRequired');

  /// See `AppStrings.authEmailInvalid`.
  String get authEmailInvalid => lookUp('authEmailInvalid');

  /// See `AppStrings.authPasswordRequired`.
  String get authPasswordRequired => lookUp('authPasswordRequired');

  /// See `AppStrings.authPasswordTooShort`.
  String get authPasswordTooShort => lookUp('authPasswordTooShort');

  /// See `AppStrings.authUpgraded`.
  String get authUpgraded => lookUp('authUpgraded');

  /// See `AppStrings.authSignOut`.
  String get authSignOut => lookUp('authSignOut');

  /// See `AppStrings.settingsAccountSection`.
  String get settingsAccountSection => lookUp('settingsAccountSection');

  /// See `AppStrings.settingsAccountGuest`.
  String get settingsAccountGuest => lookUp('settingsAccountGuest');

  /// See `AppStrings.settingsAccountLinked`.
  String get settingsAccountLinked => lookUp('settingsAccountLinked');

  /// See `AppStrings.settingsSignOutBody`.
  String get settingsSignOutBody => lookUp('settingsSignOutBody');

  /// See `AppStrings.settingsSignOutGuestBody`.
  String get settingsSignOutGuestBody => lookUp('settingsSignOutGuestBody');

  /// See `AppStrings.profileTitle`.
  String get profileTitle => lookUp('profileTitle');

  /// See `AppStrings.profileNameLabel`.
  String get profileNameLabel => lookUp('profileNameLabel');

  /// See `AppStrings.profileNameHint`.
  String get profileNameHint => lookUp('profileNameHint');

  /// See `AppStrings.profileAvatarSection`.
  String get profileAvatarSection => lookUp('profileAvatarSection');

  /// See `AppStrings.profileColorSection`.
  String get profileColorSection => lookUp('profileColorSection');

  /// See `AppStrings.profileRandomize`.
  String get profileRandomize => lookUp('profileRandomize');

  /// See `AppStrings.profileSave`.
  String get profileSave => lookUp('profileSave');

  /// See `AppStrings.profileSaved`.
  String get profileSaved => lookUp('profileSaved');

  /// See `AppStrings.profileDiscardTitle`.
  String get profileDiscardTitle => lookUp('profileDiscardTitle');

  /// See `AppStrings.profileDiscardBody`.
  String get profileDiscardBody => lookUp('profileDiscardBody');

  /// See `AppStrings.createTitle`.
  String get createTitle => lookUp('createTitle');

  /// See `AppStrings.createRulesSection`.
  String get createRulesSection => lookUp('createRulesSection');

  /// See `AppStrings.createWordsSection`.
  String get createWordsSection => lookUp('createWordsSection');

  /// See `AppStrings.createRoomSection`.
  String get createRoomSection => lookUp('createRoomSection');

  /// See `AppStrings.createMaxPlayers`.
  String get createMaxPlayers => lookUp('createMaxPlayers');

  /// See `AppStrings.createRounds`.
  String get createRounds => lookUp('createRounds');

  /// See `AppStrings.createDrawTime`.
  String get createDrawTime => lookUp('createDrawTime');

  /// See `AppStrings.createWordChoices`.
  String get createWordChoices => lookUp('createWordChoices');

  /// See `AppStrings.createHints`.
  String get createHints => lookUp('createHints');

  /// See `AppStrings.createWordSelectTime`.
  String get createWordSelectTime => lookUp('createWordSelectTime');

  /// See `AppStrings.createWordMode`.
  String get createWordMode => lookUp('createWordMode');

  /// See `AppStrings.createCustomWords`.
  String get createCustomWords => lookUp('createCustomWords');

  /// See `AppStrings.createCustomWordHint`.
  String get createCustomWordHint => lookUp('createCustomWordHint');

  /// See `AppStrings.createCustomWordsEmpty`.
  String get createCustomWordsEmpty => lookUp('createCustomWordsEmpty');

  /// See `AppStrings.createAllowVoteKick`.
  String get createAllowVoteKick => lookUp('createAllowVoteKick');

  /// See `AppStrings.createPrivate`.
  String get createPrivate => lookUp('createPrivate');

  /// See `AppStrings.createPrivateHint`.
  String get createPrivateHint => lookUp('createPrivateHint');

  /// See `AppStrings.createSubmit`.
  String get createSubmit => lookUp('createSubmit');

  /// See `AppStrings.createReset`.
  String get createReset => lookUp('createReset');

  /// See `AppStrings.joinTitle`.
  String get joinTitle => lookUp('joinTitle');

  /// See `AppStrings.joinCodeLabel`.
  String get joinCodeLabel => lookUp('joinCodeLabel');

  /// See `AppStrings.joinCodeHint`.
  String get joinCodeHint => lookUp('joinCodeHint');

  /// See `AppStrings.joinCodeHelp`.
  String get joinCodeHelp => lookUp('joinCodeHelp');

  /// See `AppStrings.joinSubmit`.
  String get joinSubmit => lookUp('joinSubmit');

  /// See `AppStrings.joinLastRoom`.
  String get joinLastRoom => lookUp('joinLastRoom');

  /// See `AppStrings.joinPaste`.
  String get joinPaste => lookUp('joinPaste');

  /// See `AppStrings.lobbyTitle`.
  String get lobbyTitle => lookUp('lobbyTitle');

  /// See `AppStrings.lobbyRoomCode`.
  String get lobbyRoomCode => lookUp('lobbyRoomCode');

  /// See `AppStrings.lobbyCopyCode`.
  String get lobbyCopyCode => lookUp('lobbyCopyCode');

  /// See `AppStrings.lobbyInvite`.
  String get lobbyInvite => lookUp('lobbyInvite');

  /// See `AppStrings.lobbyPlayers`.
  String get lobbyPlayers => lookUp('lobbyPlayers');

  /// See `AppStrings.lobbyReady`.
  String get lobbyReady => lookUp('lobbyReady');

  /// See `AppStrings.lobbyNotReady`.
  String get lobbyNotReady => lookUp('lobbyNotReady');

  /// See `AppStrings.lobbyStart`.
  String get lobbyStart => lookUp('lobbyStart');

  /// See `AppStrings.lobbySettings`.
  String get lobbySettings => lookUp('lobbySettings');

  /// See `AppStrings.lobbyWaitingForHost`.
  String get lobbyWaitingForHost => lookUp('lobbyWaitingForHost');

  /// See `AppStrings.lobbyNeedMorePlayers`.
  String get lobbyNeedMorePlayers => lookUp('lobbyNeedMorePlayers');

  /// See `AppStrings.lobbyEmptyPlayers`.
  String get lobbyEmptyPlayers => lookUp('lobbyEmptyPlayers');

  /// See `AppStrings.lobbyHostBadge`.
  String get lobbyHostBadge => lookUp('lobbyHostBadge');

  /// See `AppStrings.lobbyReadyBadge`.
  String get lobbyReadyBadge => lookUp('lobbyReadyBadge');

  /// See `AppStrings.lobbyLeaveTitle`.
  String get lobbyLeaveTitle => lookUp('lobbyLeaveTitle');

  /// See `AppStrings.lobbyLeaveBody`.
  String get lobbyLeaveBody => lookUp('lobbyLeaveBody');

  /// See `AppStrings.lobbyRoomClosed`.
  String get lobbyRoomClosed => lookUp('lobbyRoomClosed');

  /// See `AppStrings.gameTitle`.
  String get gameTitle => lookUp('gameTitle');

  /// See `AppStrings.gameGetReady`.
  String get gameGetReady => lookUp('gameGetReady');

  /// See `AppStrings.gameChooseWord`.
  String get gameChooseWord => lookUp('gameChooseWord');

  /// See `AppStrings.gameWaitingForWord`.
  String get gameWaitingForWord => lookUp('gameWaitingForWord');

  /// See `AppStrings.gameGuessThis`.
  String get gameGuessThis => lookUp('gameGuessThis');

  /// See `AppStrings.gameYouDraw`.
  String get gameYouDraw => lookUp('gameYouDraw');

  /// See `AppStrings.gameWatching`.
  String get gameWatching => lookUp('gameWatching');

  /// See `AppStrings.gameTimeUp`.
  String get gameTimeUp => lookUp('gameTimeUp');

  /// See `AppStrings.gamePaused`.
  String get gamePaused => lookUp('gamePaused');

  /// See `AppStrings.gamePausedBody`.
  String get gamePausedBody => lookUp('gamePausedBody');

  /// See `AppStrings.gameYouGuessedIt`.
  String get gameYouGuessedIt => lookUp('gameYouGuessedIt');

  /// See `AppStrings.gamePen`.
  String get gamePen => lookUp('gamePen');

  /// See `AppStrings.gameEraser`.
  String get gameEraser => lookUp('gameEraser');

  /// See `AppStrings.gameUndo`.
  String get gameUndo => lookUp('gameUndo');

  /// See `AppStrings.gameRedo`.
  String get gameRedo => lookUp('gameRedo');

  /// See `AppStrings.gameClear`.
  String get gameClear => lookUp('gameClear');

  /// See `AppStrings.gameColors`.
  String get gameColors => lookUp('gameColors');

  /// See `AppStrings.gameBrush`.
  String get gameBrush => lookUp('gameBrush');

  /// See `AppStrings.gameTools`.
  String get gameTools => lookUp('gameTools');

  /// See `AppStrings.gameToolsTitle`.
  String get gameToolsTitle => lookUp('gameToolsTitle');

  /// See `AppStrings.gameCustomColor`.
  String get gameCustomColor => lookUp('gameCustomColor');

  /// See `AppStrings.gameBrushSize`.
  String get gameBrushSize => lookUp('gameBrushSize');

  /// See `AppStrings.gameFillHint`.
  String get gameFillHint => lookUp('gameFillHint');

  /// See `AppStrings.gameClearTitle`.
  String get gameClearTitle => lookUp('gameClearTitle');

  /// See `AppStrings.gameClearBody`.
  String get gameClearBody => lookUp('gameClearBody');

  /// See `AppStrings.gameQuitTitle`.
  String get gameQuitTitle => lookUp('gameQuitTitle');

  /// See `AppStrings.gameQuitBody`.
  String get gameQuitBody => lookUp('gameQuitBody');

  /// See `AppStrings.gamePlayersSheet`.
  String get gamePlayersSheet => lookUp('gamePlayersSheet');

  /// See `AppStrings.gameChatSheet`.
  String get gameChatSheet => lookUp('gameChatSheet');

  /// See `AppStrings.chatTitle`.
  String get chatTitle => lookUp('chatTitle');

  /// See `AppStrings.chatGuessHint`.
  String get chatGuessHint => lookUp('chatGuessHint');

  /// See `AppStrings.chatDrawerHint`.
  String get chatDrawerHint => lookUp('chatDrawerHint');

  /// See `AppStrings.chatGuessedHint`.
  String get chatGuessedHint => lookUp('chatGuessedHint');

  /// See `AppStrings.chatSend`.
  String get chatSend => lookUp('chatSend');

  /// See `AppStrings.chatEmpty`.
  String get chatEmpty => lookUp('chatEmpty');

  /// See `AppStrings.chatCloseGuess`.
  String get chatCloseGuess => lookUp('chatCloseGuess');

  /// See `AppStrings.chatMuted`.
  String get chatMuted => lookUp('chatMuted');

  /// See `AppStrings.voiceDrawerStatus`.
  String get voiceDrawerStatus => lookUp('voiceDrawerStatus');

  /// See `AppStrings.voiceDrawerDisabled`.
  String get voiceDrawerDisabled => lookUp('voiceDrawerDisabled');

  /// See `AppStrings.voiceMute`.
  String get voiceMute => lookUp('voiceMute');

  /// See `AppStrings.voiceUnmute`.
  String get voiceUnmute => lookUp('voiceUnmute');

  /// See `AppStrings.voiceConnecting`.
  String get voiceConnecting => lookUp('voiceConnecting');

  /// See `AppStrings.voiceNoPermission`.
  String get voiceNoPermission => lookUp('voiceNoPermission');

  /// See `AppStrings.voicePermissionBody`.
  String get voicePermissionBody => lookUp('voicePermissionBody');

  /// See `AppStrings.voiceNoMicrophone`.
  String get voiceNoMicrophone => lookUp('voiceNoMicrophone');

  /// See `AppStrings.voiceOff`.
  String get voiceOff => lookUp('voiceOff');

  /// See `AppStrings.voiceSomeoneSpeaking`.
  String get voiceSomeoneSpeaking => lookUp('voiceSomeoneSpeaking');

  /// See `AppStrings.voiceFailed`.
  String get voiceFailed => lookUp('voiceFailed');

  /// See `AppStrings.resultsRoundTitle`.
  String get resultsRoundTitle => lookUp('resultsRoundTitle');

  /// See `AppStrings.resultsFinalTitle`.
  String get resultsFinalTitle => lookUp('resultsFinalTitle');

  /// See `AppStrings.resultsWordWas`.
  String get resultsWordWas => lookUp('resultsWordWas');

  /// See `AppStrings.resultsThisRound`.
  String get resultsThisRound => lookUp('resultsThisRound');

  /// See `AppStrings.resultsTotals`.
  String get resultsTotals => lookUp('resultsTotals');

  /// See `AppStrings.resultsNextRoundSoon`.
  String get resultsNextRoundSoon => lookUp('resultsNextRoundSoon');

  /// See `AppStrings.resultsNobodyGuessed`.
  String get resultsNobodyGuessed => lookUp('resultsNobodyGuessed');

  /// See `AppStrings.resultsPlayAgain`.
  String get resultsPlayAgain => lookUp('resultsPlayAgain');

  /// See `AppStrings.resultsBackHome`.
  String get resultsBackHome => lookUp('resultsBackHome');

  /// See `AppStrings.resultsYouWon`.
  String get resultsYouWon => lookUp('resultsYouWon');

  /// See `AppStrings.leaderboardTitle`.
  String get leaderboardTitle => lookUp('leaderboardTitle');

  /// See `AppStrings.leaderboardRank`.
  String get leaderboardRank => lookUp('leaderboardRank');

  /// See `AppStrings.leaderboardScore`.
  String get leaderboardScore => lookUp('leaderboardScore');

  /// See `AppStrings.leaderboardGames`.
  String get leaderboardGames => lookUp('leaderboardGames');

  /// See `AppStrings.leaderboardWins`.
  String get leaderboardWins => lookUp('leaderboardWins');

  /// See `AppStrings.leaderboardBestRound`.
  String get leaderboardBestRound => lookUp('leaderboardBestRound');

  /// See `AppStrings.leaderboardEmpty`.
  String get leaderboardEmpty => lookUp('leaderboardEmpty');

  /// See `AppStrings.leaderboardClear`.
  String get leaderboardClear => lookUp('leaderboardClear');

  /// See `AppStrings.leaderboardClearTitle`.
  String get leaderboardClearTitle => lookUp('leaderboardClearTitle');

  /// See `AppStrings.leaderboardClearBody`.
  String get leaderboardClearBody => lookUp('leaderboardClearBody');

  /// See `AppStrings.settingsTitle`.
  String get settingsTitle => lookUp('settingsTitle');

  /// See `AppStrings.settingsFeedbackSection`.
  String get settingsFeedbackSection => lookUp('settingsFeedbackSection');

  /// See `AppStrings.settingsAppearanceSection`.
  String get settingsAppearanceSection => lookUp('settingsAppearanceSection');

  /// See `AppStrings.settingsAboutSection`.
  String get settingsAboutSection => lookUp('settingsAboutSection');

  /// See `AppStrings.settingsSound`.
  String get settingsSound => lookUp('settingsSound');

  /// See `AppStrings.settingsHaptics`.
  String get settingsHaptics => lookUp('settingsHaptics');

  /// See `AppStrings.settingsReducedMotion`.
  String get settingsReducedMotion => lookUp('settingsReducedMotion');

  /// See `AppStrings.settingsReducedMotionHint`.
  String get settingsReducedMotionHint => lookUp('settingsReducedMotionHint');

  /// See `AppStrings.settingsTheme`.
  String get settingsTheme => lookUp('settingsTheme');

  /// See `AppStrings.settingsThemeLight`.
  String get settingsThemeLight => lookUp('settingsThemeLight');

  /// See `AppStrings.settingsThemeDark`.
  String get settingsThemeDark => lookUp('settingsThemeDark');

  /// See `AppStrings.settingsThemeSystem`.
  String get settingsThemeSystem => lookUp('settingsThemeSystem');

  /// See `AppStrings.settingsLanguageSection`.
  String get settingsLanguageSection => lookUp('settingsLanguageSection');

  /// See `AppStrings.settingsLanguage`.
  String get settingsLanguage => lookUp('settingsLanguage');

  /// See `AppStrings.settingsLanguageHint`.
  String get settingsLanguageHint => lookUp('settingsLanguageHint');

  /// See `AppStrings.settingsVersion`.
  String get settingsVersion => lookUp('settingsVersion');

  /// See `AppStrings.settingsResetAll`.
  String get settingsResetAll => lookUp('settingsResetAll');

  /// See `AppStrings.settingsResetTitle`.
  String get settingsResetTitle => lookUp('settingsResetTitle');

  /// See `AppStrings.settingsResetBody`.
  String get settingsResetBody => lookUp('settingsResetBody');

  /// See `AppStrings.howToPlayTitle`.
  String get howToPlayTitle => lookUp('howToPlayTitle');

  /// See `AppStrings.howToPlayIntro`.
  String get howToPlayIntro => lookUp('howToPlayIntro');

  /// See `AppStrings.howToPlayTurnsTitle`.
  String get howToPlayTurnsTitle => lookUp('howToPlayTurnsTitle');

  /// See `AppStrings.howToPlayTurnsBody`.
  String get howToPlayTurnsBody => lookUp('howToPlayTurnsBody');

  /// See `AppStrings.howToPlayWordTitle`.
  String get howToPlayWordTitle => lookUp('howToPlayWordTitle');

  /// See `AppStrings.howToPlayWordBody`.
  String get howToPlayWordBody => lookUp('howToPlayWordBody');

  /// See `AppStrings.howToPlayDrawTitle`.
  String get howToPlayDrawTitle => lookUp('howToPlayDrawTitle');

  /// See `AppStrings.howToPlayDrawBody`.
  String get howToPlayDrawBody => lookUp('howToPlayDrawBody');

  /// See `AppStrings.howToPlayGuessTitle`.
  String get howToPlayGuessTitle => lookUp('howToPlayGuessTitle');

  /// See `AppStrings.howToPlayGuessBody`.
  String get howToPlayGuessBody => lookUp('howToPlayGuessBody');

  /// See `AppStrings.howToPlayScoreTitle`.
  String get howToPlayScoreTitle => lookUp('howToPlayScoreTitle');

  /// See `AppStrings.howToPlayScoreBody`.
  String get howToPlayScoreBody => lookUp('howToPlayScoreBody');

  /// See `AppStrings.howToPlayHintTitle`.
  String get howToPlayHintTitle => lookUp('howToPlayHintTitle');

  /// See `AppStrings.howToPlayHintBody`.
  String get howToPlayHintBody => lookUp('howToPlayHintBody');

  /// See `AppStrings.howToPlayFairTitle`.
  String get howToPlayFairTitle => lookUp('howToPlayFairTitle');

  /// See `AppStrings.howToPlayFairBody`.
  String get howToPlayFairBody => lookUp('howToPlayFairBody');

  /// See `AppStrings.moderationKick`.
  String get moderationKick => lookUp('moderationKick');

  /// See `AppStrings.moderationBan`.
  String get moderationBan => lookUp('moderationBan');

  /// See `AppStrings.moderationMute`.
  String get moderationMute => lookUp('moderationMute');

  /// See `AppStrings.moderationUnmute`.
  String get moderationUnmute => lookUp('moderationUnmute');

  /// See `AppStrings.moderationTransferHost`.
  String get moderationTransferHost => lookUp('moderationTransferHost');

  /// See `AppStrings.moderationVoteKick`.
  String get moderationVoteKick => lookUp('moderationVoteKick');

  /// See `AppStrings.moderationReport`.
  String get moderationReport => lookUp('moderationReport');

  /// See `AppStrings.moderationKickTitle`.
  String get moderationKickTitle => lookUp('moderationKickTitle');

  /// See `AppStrings.moderationKickBody`.
  String get moderationKickBody => lookUp('moderationKickBody');

  /// See `AppStrings.moderationBanTitle`.
  String get moderationBanTitle => lookUp('moderationBanTitle');

  /// See `AppStrings.moderationBanBody`.
  String get moderationBanBody => lookUp('moderationBanBody');

  /// See `AppStrings.moderationTransferTitle`.
  String get moderationTransferTitle => lookUp('moderationTransferTitle');

  /// See `AppStrings.moderationTransferBody`.
  String get moderationTransferBody => lookUp('moderationTransferBody');

  /// See `AppStrings.moderationReportTitle`.
  String get moderationReportTitle => lookUp('moderationReportTitle');

  /// See `AppStrings.moderationReportHint`.
  String get moderationReportHint => lookUp('moderationReportHint');

  /// See `AppStrings.moderationReportSent`.
  String get moderationReportSent => lookUp('moderationReportSent');

  /// See `AppStrings.moderationYouWereKicked`.
  String get moderationYouWereKicked => lookUp('moderationYouWereKicked');

  /// See `AppStrings.moderationYouWereBanned`.
  String get moderationYouWereBanned => lookUp('moderationYouWereBanned');

  /// See `AppStrings.errorUnknown`.
  String get errorUnknown => lookUp('errorUnknown');

  /// See `AppStrings.errorNetwork`.
  String get errorNetwork => lookUp('errorNetwork');

  /// See `AppStrings.errorTimeout`.
  String get errorTimeout => lookUp('errorTimeout');

  /// See `AppStrings.errorServer`.
  String get errorServer => lookUp('errorServer');

  /// See `AppStrings.errorConnectionLost`.
  String get errorConnectionLost => lookUp('errorConnectionLost');

  /// See `AppStrings.errorRoomNotFound`.
  String get errorRoomNotFound => lookUp('errorRoomNotFound');

  /// See `AppStrings.errorRoomFull`.
  String get errorRoomFull => lookUp('errorRoomFull');

  /// See `AppStrings.errorGameInProgress`.
  String get errorGameInProgress => lookUp('errorGameInProgress');

  /// See `AppStrings.errorNameTaken`.
  String get errorNameTaken => lookUp('errorNameTaken');

  /// See `AppStrings.errorInvalidCode`.
  String get errorInvalidCode => lookUp('errorInvalidCode');

  /// See `AppStrings.errorBanned`.
  String get errorBanned => lookUp('errorBanned');

  /// See `AppStrings.errorKicked`.
  String get errorKicked => lookUp('errorKicked');

  /// See `AppStrings.errorNotHost`.
  String get errorNotHost => lookUp('errorNotHost');

  /// See `AppStrings.errorNotDrawer`.
  String get errorNotDrawer => lookUp('errorNotDrawer');

  /// See `AppStrings.errorInvalidAction`.
  String get errorInvalidAction => lookUp('errorInvalidAction');

  /// See `AppStrings.errorValidation`.
  String get errorValidation => lookUp('errorValidation');

  /// See `AppStrings.errorStorage`.
  String get errorStorage => lookUp('errorStorage');

  /// See `AppStrings.errorConnectionTitle`.
  String get errorConnectionTitle => lookUp('errorConnectionTitle');

  /// See `AppStrings.errorRealtimeUnreachable`.
  String get errorRealtimeUnreachable => lookUp('errorRealtimeUnreachable');

  /// See `AppStrings.errorBackendDegraded`.
  String get errorBackendDegraded => lookUp('errorBackendDegraded');

  /// See `AppStrings.errorRoomNotFoundTitle`.
  String get errorRoomNotFoundTitle => lookUp('errorRoomNotFoundTitle');

  /// See `AppStrings.errorRoomFullTitle`.
  String get errorRoomFullTitle => lookUp('errorRoomFullTitle');

  /// See `AppStrings.statusConnecting`.
  String get statusConnecting => lookUp('statusConnecting');

  /// See `AppStrings.statusReconnecting`.
  String get statusReconnecting => lookUp('statusReconnecting');

  /// See `AppStrings.statusOffline`.
  String get statusOffline => lookUp('statusOffline');

  /// See `AppStrings.statusConnected`.
  String get statusConnected => lookUp('statusConnected');

  /// See `AppStrings.validationNameRequired`.
  String get validationNameRequired => lookUp('validationNameRequired');

  /// See `AppStrings.validationNameTooShort`.
  String get validationNameTooShort => lookUp('validationNameTooShort');

  /// See `AppStrings.validationNameTooLong`.
  String get validationNameTooLong => lookUp('validationNameTooLong');

  /// See `AppStrings.validationNameInvalid`.
  String get validationNameInvalid => lookUp('validationNameInvalid');

  /// See `AppStrings.validationCodeRequired`.
  String get validationCodeRequired => lookUp('validationCodeRequired');

  /// See `AppStrings.validationCodeLength`.
  String get validationCodeLength => lookUp('validationCodeLength');

  /// See `AppStrings.validationCodeInvalid`.
  String get validationCodeInvalid => lookUp('validationCodeInvalid');

  /// See `AppStrings.validationMessageRequired`.
  String get validationMessageRequired => lookUp('validationMessageRequired');

  /// See `AppStrings.validationMessageTooLong`.
  String get validationMessageTooLong => lookUp('validationMessageTooLong');

  /// See `AppStrings.validationWordRequired`.
  String get validationWordRequired => lookUp('validationWordRequired');

  /// See `AppStrings.validationWordTooShort`.
  String get validationWordTooShort => lookUp('validationWordTooShort');

  /// See `AppStrings.validationWordTooLong`.
  String get validationWordTooLong => lookUp('validationWordTooLong');

  /// See `AppStrings.validationWordInvalid`.
  String get validationWordInvalid => lookUp('validationWordInvalid');

  /// See `AppStrings.validationUrlRequired`.
  String get validationUrlRequired => lookUp('validationUrlRequired');

  /// See `AppStrings.validationUrlInvalid`.
  String get validationUrlInvalid => lookUp('validationUrlInvalid');

  /// See `AppStrings.a11yBack`.
  String get a11yBack => lookUp('a11yBack');

  /// See `AppStrings.a11yClose`.
  String get a11yClose => lookUp('a11yClose');

  /// See `AppStrings.a11ySettings`.
  String get a11ySettings => lookUp('a11ySettings');

  /// See `AppStrings.a11yAvatar`.
  String get a11yAvatar => lookUp('a11yAvatar');

  /// See `AppStrings.a11yHost`.
  String get a11yHost => lookUp('a11yHost');

  /// See `AppStrings.a11yDrawing`.
  String get a11yDrawing => lookUp('a11yDrawing');

  /// See `AppStrings.a11yGuessedCorrectly`.
  String get a11yGuessedCorrectly => lookUp('a11yGuessedCorrectly');

  /// See `AppStrings.a11yConnection`.
  String get a11yConnection => lookUp('a11yConnection');

  /// See `AppStrings.a11yTimer`.
  String get a11yTimer => lookUp('a11yTimer');

  /// See `AppStrings.a11yCanvasDrawer`.
  String get a11yCanvasDrawer => lookUp('a11yCanvasDrawer');

  /// See `AppStrings.a11yCanvasViewer`.
  String get a11yCanvasViewer => lookUp('a11yCanvasViewer');

  /// See `AppStrings.a11yColorPicker`.
  String get a11yColorPicker => lookUp('a11yColorPicker');

  /// See `AppStrings.a11yBrushPicker`.
  String get a11yBrushPicker => lookUp('a11yBrushPicker');

  /// See `AppStrings.a11yChatList`.
  String get a11yChatList => lookUp('a11yChatList');

  /// See `AppStrings.a11yScoreBoard`.
  String get a11yScoreBoard => lookUp('a11yScoreBoard');

  /// See `AppStrings.a11yPlayerMenu`.
  String get a11yPlayerMenu => lookUp('a11yPlayerMenu');

  /// See `AppStrings.timeNow`.
  String get timeNow => lookUp('timeNow');

  /// See `AppStrings.timeSecondsSuffix`.
  String get timeSecondsSuffix => lookUp('timeSecondsSuffix');

  /// See `AppStrings.timeMinutesSuffix`.
  String get timeMinutesSuffix => lookUp('timeMinutesSuffix');

  /// See `AppStrings.timeHoursSuffix`.
  String get timeHoursSuffix => lookUp('timeHoursSuffix');

  /// See `AppStrings.timeDaysSuffix`.
  String get timeDaysSuffix => lookUp('timeDaysSuffix');

  /// See `AppStrings.timeWeeksSuffix`.
  String get timeWeeksSuffix => lookUp('timeWeeksSuffix');

  /// See `AppStrings.timeYearsSuffix`.
  String get timeYearsSuffix => lookUp('timeYearsSuffix');

  /// See `AppStrings.quickPlay`.
  String get quickPlay => lookUp('quickPlay');

  /// See `AppStrings.quickPlayHint`.
  String get quickPlayHint => lookUp('quickPlayHint');

  /// See `AppStrings.quickPlayConnecting`.
  String get quickPlayConnecting => lookUp('quickPlayConnecting');

  /// See `AppStrings.quickPlayFinding`.
  String get quickPlayFinding => lookUp('quickPlayFinding');

  /// See `AppStrings.quickPlayJoining`.
  String get quickPlayJoining => lookUp('quickPlayJoining');

  /// See `AppStrings.quickPlayCreating`.
  String get quickPlayCreating => lookUp('quickPlayCreating');

  /// See `AppStrings.quickPlayFailed`.
  String get quickPlayFailed => lookUp('quickPlayFailed');

  /// See `AppStrings.quickPlayOpened`.
  String get quickPlayOpened => lookUp('quickPlayOpened');

  /// See `AppStrings.leaderboardWinRate`.
  String get leaderboardWinRate => lookUp('leaderboardWinRate');

  /// See `AppStrings.leaderboardYourRank`.
  String get leaderboardYourRank => lookUp('leaderboardYourRank');

  /// See `AppStrings.leaderboardUnranked`.
  String get leaderboardUnranked => lookUp('leaderboardUnranked');

  /// See `AppStrings.leaderboardFriendsEmpty`.
  String get leaderboardFriendsEmpty => lookUp('leaderboardFriendsEmpty');

  /// See `AppStrings.leaderboardLocalityEmpty`.
  String get leaderboardLocalityEmpty => lookUp('leaderboardLocalityEmpty');

  /// See `AppStrings.leaderboardNeedsLocality`.
  String get leaderboardNeedsLocality => lookUp('leaderboardNeedsLocality');

  /// See `AppStrings.leaderboardSetLocality`.
  String get leaderboardSetLocality => lookUp('leaderboardSetLocality');

  /// See `AppStrings.leaderboardLocalHistory`.
  String get leaderboardLocalHistory => lookUp('leaderboardLocalHistory');

  /// See `AppStrings.friendsTitle`.
  String get friendsTitle => lookUp('friendsTitle');

  /// See `AppStrings.friendsTabFriends`.
  String get friendsTabFriends => lookUp('friendsTabFriends');

  /// See `AppStrings.friendsTabRequests`.
  String get friendsTabRequests => lookUp('friendsTabRequests');

  /// See `AppStrings.friendsTabBlocked`.
  String get friendsTabBlocked => lookUp('friendsTabBlocked');

  /// See `AppStrings.friendRequestsTitle`.
  String get friendRequestsTitle => lookUp('friendRequestsTitle');

  /// See `AppStrings.friendRequestsIncoming`.
  String get friendRequestsIncoming => lookUp('friendRequestsIncoming');

  /// See `AppStrings.friendRequestsOutgoing`.
  String get friendRequestsOutgoing => lookUp('friendRequestsOutgoing');

  /// See `AppStrings.friendsEmpty`.
  String get friendsEmpty => lookUp('friendsEmpty');

  /// See `AppStrings.friendRequestsEmpty`.
  String get friendRequestsEmpty => lookUp('friendRequestsEmpty');

  /// See `AppStrings.friendsBlockedEmpty`.
  String get friendsBlockedEmpty => lookUp('friendsBlockedEmpty');

  /// See `AppStrings.friendsSearchHint`.
  String get friendsSearchHint => lookUp('friendsSearchHint');

  /// See `AppStrings.friendsSearchEmpty`.
  String get friendsSearchEmpty => lookUp('friendsSearchEmpty');

  /// See `AppStrings.friendsSearchPrompt`.
  String get friendsSearchPrompt => lookUp('friendsSearchPrompt');

  /// See `AppStrings.friendAdd`.
  String get friendAdd => lookUp('friendAdd');

  /// See `AppStrings.friendRequested`.
  String get friendRequested => lookUp('friendRequested');

  /// See `AppStrings.friendCancelRequest`.
  String get friendCancelRequest => lookUp('friendCancelRequest');

  /// See `AppStrings.friendAccept`.
  String get friendAccept => lookUp('friendAccept');

  /// See `AppStrings.friendReject`.
  String get friendReject => lookUp('friendReject');

  /// See `AppStrings.friendsAlready`.
  String get friendsAlready => lookUp('friendsAlready');

  /// See `AppStrings.friendRemove`.
  String get friendRemove => lookUp('friendRemove');

  /// See `AppStrings.friendBlock`.
  String get friendBlock => lookUp('friendBlock');

  /// See `AppStrings.friendBlocked`.
  String get friendBlocked => lookUp('friendBlocked');

  /// See `AppStrings.friendUnblock`.
  String get friendUnblock => lookUp('friendUnblock');

  /// See `AppStrings.friendRemoveTitle`.
  String get friendRemoveTitle => lookUp('friendRemoveTitle');

  /// See `AppStrings.friendBlockTitle`.
  String get friendBlockTitle => lookUp('friendBlockTitle');

  /// See `AppStrings.friendBlockBody`.
  String get friendBlockBody => lookUp('friendBlockBody');

  /// See `AppStrings.friendUnblockTitle`.
  String get friendUnblockTitle => lookUp('friendUnblockTitle');

  /// See `AppStrings.friendUnblockBody`.
  String get friendUnblockBody => lookUp('friendUnblockBody');

  /// See `AppStrings.playerProfileTitle`.
  String get playerProfileTitle => lookUp('playerProfileTitle');

  /// See `AppStrings.playerProfileRank`.
  String get playerProfileRank => lookUp('playerProfileRank');

  /// See `AppStrings.playerProfileUnranked`.
  String get playerProfileUnranked => lookUp('playerProfileUnranked');

  /// See `AppStrings.playerProfileLocality`.
  String get playerProfileLocality => lookUp('playerProfileLocality');

  /// See `AppStrings.localitySection`.
  String get localitySection => lookUp('localitySection');

  /// See `AppStrings.localityHint`.
  String get localityHint => lookUp('localityHint');

  /// See `AppStrings.localityCity`.
  String get localityCity => lookUp('localityCity');

  /// See `AppStrings.localityRegion`.
  String get localityRegion => lookUp('localityRegion');

  /// See `AppStrings.localityCountry`.
  String get localityCountry => lookUp('localityCountry');

  /// See `AppStrings.localityCountryHint`.
  String get localityCountryHint => lookUp('localityCountryHint');

  /// See `AppStrings.locationUse`.
  String get locationUse => lookUp('locationUse');

  /// See `AppStrings.locationUpdate`.
  String get locationUpdate => lookUp('locationUpdate');

  /// See `AppStrings.settingsLocationSection`.
  String get settingsLocationSection => lookUp('settingsLocationSection');

  /// See `AppStrings.locationSettingsRow`.
  String get locationSettingsRow => lookUp('locationSettingsRow');

  /// See `AppStrings.locationSettingsHint`.
  String get locationSettingsHint => lookUp('locationSettingsHint');

  /// See `AppStrings.locationDetecting`.
  String get locationDetecting => lookUp('locationDetecting');

  /// See `AppStrings.locationNoticeTitle`.
  String get locationNoticeTitle => lookUp('locationNoticeTitle');

  /// See `AppStrings.locationNoticeBody`.
  String get locationNoticeBody => lookUp('locationNoticeBody');

  /// See `AppStrings.locationNoticeAllow`.
  String get locationNoticeAllow => lookUp('locationNoticeAllow');

  /// See `AppStrings.locationNoticeNotNow`.
  String get locationNoticeNotNow => lookUp('locationNoticeNotNow');

  /// See `AppStrings.locationSaved`.
  String get locationSaved => lookUp('locationSaved');

  /// See `AppStrings.locationDeniedHint`.
  String get locationDeniedHint => lookUp('locationDeniedHint');

  /// See `AppStrings.locationBlockedTitle`.
  String get locationBlockedTitle => lookUp('locationBlockedTitle');

  /// See `AppStrings.locationBlockedBody`.
  String get locationBlockedBody => lookUp('locationBlockedBody');

  /// See `AppStrings.locationOpenSettings`.
  String get locationOpenSettings => lookUp('locationOpenSettings');

  /// See `AppStrings.locationOffTitle`.
  String get locationOffTitle => lookUp('locationOffTitle');

  /// See `AppStrings.locationOffBody`.
  String get locationOffBody => lookUp('locationOffBody');

  /// See `AppStrings.locationNotFound`.
  String get locationNotFound => lookUp('locationNotFound');

  /// See `AppStrings.locationFailed`.
  String get locationFailed => lookUp('locationFailed');

  /// See `AppStrings.locationUnsupported`.
  String get locationUnsupported => lookUp('locationUnsupported');

  /// See `AppStrings.locationEnterManually`.
  String get locationEnterManually => lookUp('locationEnterManually');

  /// See `AppStrings.locationHideManual`.
  String get locationHideManual => lookUp('locationHideManual');

  /// See `AppStrings.locationClear`.
  String get locationClear => lookUp('locationClear');

  /// See `AppStrings.locationClearTitle`.
  String get locationClearTitle => lookUp('locationClearTitle');

  /// See `AppStrings.locationClearBody`.
  String get locationClearBody => lookUp('locationClearBody');

  /// See `AppStrings.locationCleared`.
  String get locationCleared => lookUp('locationCleared');

  /// See `AppStrings.locationCurrent`.
  String get locationCurrent => lookUp('locationCurrent');

  /// See `AppStrings.locationNoneSet`.
  String get locationNoneSet => lookUp('locationNoneSet');

  /// See `AppStrings.inviteSheetTitle`.
  String get inviteSheetTitle => lookUp('inviteSheetTitle');

  /// See `AppStrings.inviteSheetSubtitle`.
  String get inviteSheetSubtitle => lookUp('inviteSheetSubtitle');

  /// See `AppStrings.inviteAction`.
  String get inviteAction => lookUp('inviteAction');

  /// See `AppStrings.inviteSent`.
  String get inviteSent => lookUp('inviteSent');

  /// See `AppStrings.inviteJoined`.
  String get inviteJoined => lookUp('inviteJoined');

  /// See `AppStrings.inviteOnline`.
  String get inviteOnline => lookUp('inviteOnline');

  /// See `AppStrings.inviteOffline`.
  String get inviteOffline => lookUp('inviteOffline');

  /// See `AppStrings.inviteNoFriends`.
  String get inviteNoFriends => lookUp('inviteNoFriends');

  /// See `AppStrings.inviteSentToast`.
  String get inviteSentToast => lookUp('inviteSentToast');

  /// See `AppStrings.invitationsTitle`.
  String get invitationsTitle => lookUp('invitationsTitle');

  /// See `AppStrings.invitationTitle`.
  String get invitationTitle => lookUp('invitationTitle');

  /// See `AppStrings.invitationAccept`.
  String get invitationAccept => lookUp('invitationAccept');

  /// See `AppStrings.invitationReject`.
  String get invitationReject => lookUp('invitationReject');

  /// See `AppStrings.invitationLater`.
  String get invitationLater => lookUp('invitationLater');

  /// See `AppStrings.invitationsEmpty`.
  String get invitationsEmpty => lookUp('invitationsEmpty');

  /// See `AppStrings.invitationRoom`.
  String get invitationRoom => lookUp('invitationRoom');

  /// See `AppStrings.invitationPlayers`.
  String get invitationPlayers => lookUp('invitationPlayers');

  /// See `AppStrings.invitationPublic`.
  String get invitationPublic => lookUp('invitationPublic');

  /// See `AppStrings.invitationPrivate`.
  String get invitationPrivate => lookUp('invitationPrivate');

  /// See `AppStrings.invitationRejected`.
  String get invitationRejected => lookUp('invitationRejected');

  /// See `AppStrings.publicRoomsTitle`.
  String get publicRoomsTitle => lookUp('publicRoomsTitle');

  /// See `AppStrings.publicRoomsSubtitle`.
  String get publicRoomsSubtitle => lookUp('publicRoomsSubtitle');

  /// See `AppStrings.publicRoomsEmpty`.
  String get publicRoomsEmpty => lookUp('publicRoomsEmpty');

  /// See `AppStrings.publicRoomsJoin`.
  String get publicRoomsJoin => lookUp('publicRoomsJoin');

  /// See `AppStrings.publicRoomsHostedBy`.
  String get publicRoomsHostedBy => lookUp('publicRoomsHostedBy');

  /// See `AppStrings.publicRoomsLeaveFirst`.
  String get publicRoomsLeaveFirst => lookUp('publicRoomsLeaveFirst');

  /// See `AppStrings.publicRoomsBackToRoom`.
  String get publicRoomsBackToRoom => lookUp('publicRoomsBackToRoom');

  /// See `AppStrings.roomMembersTitle`.
  String get roomMembersTitle => lookUp('roomMembersTitle');

  /// See `AppStrings.notificationsTitle`.
  String get notificationsTitle => lookUp('notificationsTitle');

  /// See `AppStrings.notificationsOpen`.
  String get notificationsOpen => lookUp('notificationsOpen');

  /// See `AppStrings.notificationsEmpty`.
  String get notificationsEmpty => lookUp('notificationsEmpty');

  /// See `AppStrings.notificationsAllRead`.
  String get notificationsAllRead => lookUp('notificationsAllRead');

  /// See `AppStrings.notificationsUnreadOnly`.
  String get notificationsUnreadOnly => lookUp('notificationsUnreadOnly');

  /// See `AppStrings.notificationsMarkAllRead`.
  String get notificationsMarkAllRead => lookUp('notificationsMarkAllRead');

  /// See `AppStrings.notificationsAllMarkedRead`.
  String get notificationsAllMarkedRead => lookUp('notificationsAllMarkedRead');

  /// See `AppStrings.notificationsDelete`.
  String get notificationsDelete => lookUp('notificationsDelete');

  /// See `AppStrings.resultShare`.
  String get resultShare => lookUp('resultShare');

  /// See `AppStrings.resultCopy`.
  String get resultCopy => lookUp('resultCopy');

  /// See `AppStrings.resultCopied`.
  String get resultCopied => lookUp('resultCopied');

  /// See `AppStrings.resultShareFailed`.
  String get resultShareFailed => lookUp('resultShareFailed');

  /// See `AppStrings.resultAwards`.
  String get resultAwards => lookUp('resultAwards');

  /// See `AppStrings.resultTopScorer`.
  String get resultTopScorer => lookUp('resultTopScorer');

  /// See `AppStrings.resultBestDrawer`.
  String get resultBestDrawer => lookUp('resultBestDrawer');

  /// See `AppStrings.resultBestGuesser`.
  String get resultBestGuesser => lookUp('resultBestGuesser');

  /// See `AppStrings.resultFastestGuesser`.
  String get resultFastestGuesser => lookUp('resultFastestGuesser');

  /// See `AppStrings.notificationsDeleted`.
  String get notificationsDeleted => lookUp('notificationsDeleted');

  /// See `AppStrings.chatTypingMany`.
  String get chatTypingMany => lookUp('chatTypingMany');

  /// See `AppStrings.chatDelete`.
  String get chatDelete => lookUp('chatDelete');

  /// See `AppStrings.chatReport`.
  String get chatReport => lookUp('chatReport');

  /// See `AppStrings.chatReported`.
  String get chatReported => lookUp('chatReported');

  /// See `AppStrings.chatDisabled`.
  String get chatDisabled => lookUp('chatDisabled');

  /// See `AppStrings.replayTitle`.
  String get replayTitle => lookUp('replayTitle');

  /// See `AppStrings.replayWatch`.
  String get replayWatch => lookUp('replayWatch');

  /// See `AppStrings.replayWord`.
  String get replayWord => lookUp('replayWord');

  /// See `AppStrings.replayDrawnBy`.
  String get replayDrawnBy => lookUp('replayDrawnBy');

  /// See `AppStrings.replayPlay`.
  String get replayPlay => lookUp('replayPlay');

  /// See `AppStrings.replayPause`.
  String get replayPause => lookUp('replayPause');

  /// See `AppStrings.replayRestart`.
  String get replayRestart => lookUp('replayRestart');

  /// See `AppStrings.replaySpeed`.
  String get replaySpeed => lookUp('replaySpeed');

  /// See `AppStrings.replayShare`.
  String get replayShare => lookUp('replayShare');

  /// See `AppStrings.replaySharing`.
  String get replaySharing => lookUp('replaySharing');

  /// See `AppStrings.replayShareFailed`.
  String get replayShareFailed => lookUp('replayShareFailed');

  /// See `AppStrings.replayNoDrawing`.
  String get replayNoDrawing => lookUp('replayNoDrawing');

  /// See `AppStrings.replayUnavailable`.
  String get replayUnavailable => lookUp('replayUnavailable');

  /// See `AppStrings.replayListEmpty`.
  String get replayListEmpty => lookUp('replayListEmpty');

  /// See `AppStrings.replayCompacted`.
  String get replayCompacted => lookUp('replayCompacted');

  /// See `AppStrings.achievementsTitle`.
  String get achievementsTitle => lookUp('achievementsTitle');

  /// See `AppStrings.achievementsEmpty`.
  String get achievementsEmpty => lookUp('achievementsEmpty');

  /// See `AppStrings.xpHistoryTitle`.
  String get xpHistoryTitle => lookUp('xpHistoryTitle');

  /// See `AppStrings.xpHistoryEmpty`.
  String get xpHistoryEmpty => lookUp('xpHistoryEmpty');

  /// See `AppStrings.progressionEarned`.
  String get progressionEarned => lookUp('progressionEarned');

  /// See `AppStrings.progressionUnlocked`.
  String get progressionUnlocked => lookUp('progressionUnlocked');

  /// See `AppStrings.progressionViewAchievements`.
  String get progressionViewAchievements => lookUp('progressionViewAchievements');

  /// See `AppStrings.practiceTitle`.
  String get practiceTitle => lookUp('practiceTitle');

  /// See `AppStrings.practiceSubtitle`.
  String get practiceSubtitle => lookUp('practiceSubtitle');

  /// See `AppStrings.practiceChooseWord`.
  String get practiceChooseWord => lookUp('practiceChooseWord');

  /// See `AppStrings.practiceScore`.
  String get practiceScore => lookUp('practiceScore');

  /// See `AppStrings.practiceGuessHint`.
  String get practiceGuessHint => lookUp('practiceGuessHint');

  /// See `AppStrings.practiceClose`.
  String get practiceClose => lookUp('practiceClose');

  /// See `AppStrings.practiceWrong`.
  String get practiceWrong => lookUp('practiceWrong');

  /// See `AppStrings.practiceGotIt`.
  String get practiceGotIt => lookUp('practiceGotIt');

  /// See `AppStrings.practiceTimeUp`.
  String get practiceTimeUp => lookUp('practiceTimeUp');

  /// See `AppStrings.practiceNextWord`.
  String get practiceNextWord => lookUp('practiceNextWord');

  /// See `AppStrings.practiceGiveUp`.
  String get practiceGiveUp => lookUp('practiceGiveUp');

  /// See `AppStrings.practiceTools`.
  String get practiceTools => lookUp('practiceTools');

  /// See `AppStrings.practiceUndo`.
  String get practiceUndo => lookUp('practiceUndo');

  /// See `AppStrings.practiceClear`.
  String get practiceClear => lookUp('practiceClear');

  /// See `AppStrings.tournamentsTitle`.
  String get tournamentsTitle => lookUp('tournamentsTitle');

  /// See `AppStrings.tournamentsEmpty`.
  String get tournamentsEmpty => lookUp('tournamentsEmpty');

  /// See `AppStrings.tournamentRegister`.
  String get tournamentRegister => lookUp('tournamentRegister');

  /// See `AppStrings.tournamentRegistered`.
  String get tournamentRegistered => lookUp('tournamentRegistered');

  /// See `AppStrings.tournamentRegisteredShort`.
  String get tournamentRegisteredShort => lookUp('tournamentRegisteredShort');

  /// See `AppStrings.tournamentEntrants`.
  String get tournamentEntrants => lookUp('tournamentEntrants');

  /// See `AppStrings.tournamentWinner`.
  String get tournamentWinner => lookUp('tournamentWinner');

  /// See `AppStrings.tournamentShowBoard`.
  String get tournamentShowBoard => lookUp('tournamentShowBoard');

  /// See `AppStrings.tournamentHideBoard`.
  String get tournamentHideBoard => lookUp('tournamentHideBoard');

  /// See `AppStrings.tournamentBoardEmpty`.
  String get tournamentBoardEmpty => lookUp('tournamentBoardEmpty');

  /// See `AppStrings.tournamentAutoSubtitle`.
  String get tournamentAutoSubtitle => lookUp('tournamentAutoSubtitle');

  /// See `AppStrings.tournamentSlotEmpty`.
  String get tournamentSlotEmpty => lookUp('tournamentSlotEmpty');

  /// See `AppStrings.tournamentSlotEmptyHint`.
  String get tournamentSlotEmptyHint => lookUp('tournamentSlotEmptyHint');

  /// See `AppStrings.tournamentNoneRunning`.
  String get tournamentNoneRunning => lookUp('tournamentNoneRunning');

  /// See `AppStrings.tournamentNoneRunningHint`.
  String get tournamentNoneRunningHint => lookUp('tournamentNoneRunningHint');

  /// See `AppStrings.tournamentNoneToday`.
  String get tournamentNoneToday => lookUp('tournamentNoneToday');

  /// See `AppStrings.tournamentNoneTodayHint`.
  String get tournamentNoneTodayHint => lookUp('tournamentNoneTodayHint');

  /// See `AppStrings.tournamentSlot`.
  String get tournamentSlot => lookUp('tournamentSlot');

  /// See `AppStrings.tournamentStatusRegistration`.
  String get tournamentStatusRegistration => lookUp('tournamentStatusRegistration');

  /// See `AppStrings.tournamentStatusCheckIn`.
  String get tournamentStatusCheckIn => lookUp('tournamentStatusCheckIn');

  /// See `AppStrings.tournamentStatusRunning`.
  String get tournamentStatusRunning => lookUp('tournamentStatusRunning');

  /// See `AppStrings.tournamentStatusUpcoming`.
  String get tournamentStatusUpcoming => lookUp('tournamentStatusUpcoming');

  /// See `AppStrings.tournamentStatusCompleted`.
  String get tournamentStatusCompleted => lookUp('tournamentStatusCompleted');

  /// See `AppStrings.tournamentStatusCancelled`.
  String get tournamentStatusCancelled => lookUp('tournamentStatusCancelled');

  /// See `AppStrings.tournamentJoin`.
  String get tournamentJoin => lookUp('tournamentJoin');

  /// See `AppStrings.tournamentCheckIn`.
  String get tournamentCheckIn => lookUp('tournamentCheckIn');

  /// See `AppStrings.tournamentCheckedIn`.
  String get tournamentCheckedIn => lookUp('tournamentCheckedIn');

  /// See `AppStrings.tournamentCheckedInShort`.
  String get tournamentCheckedInShort => lookUp('tournamentCheckedInShort');

  /// See `AppStrings.tournamentWithdraw`.
  String get tournamentWithdraw => lookUp('tournamentWithdraw');

  /// See `AppStrings.tournamentWithdrew`.
  String get tournamentWithdrew => lookUp('tournamentWithdrew');

  /// See `AppStrings.tournamentViewBracket`.
  String get tournamentViewBracket => lookUp('tournamentViewBracket');

  /// See `AppStrings.tournamentDetails`.
  String get tournamentDetails => lookUp('tournamentDetails');

  /// See `AppStrings.tournamentEnterMatch`.
  String get tournamentEnterMatch => lookUp('tournamentEnterMatch');

  /// See `AppStrings.tournamentPlayers`.
  String get tournamentPlayers => lookUp('tournamentPlayers');

  /// See `AppStrings.tournamentHumanPlayers`.
  String get tournamentHumanPlayers => lookUp('tournamentHumanPlayers');

  /// See `AppStrings.tournamentAiPlayers`.
  String get tournamentAiPlayers => lookUp('tournamentAiPlayers');

  /// See `AppStrings.tournamentAiPlayer`.
  String get tournamentAiPlayer => lookUp('tournamentAiPlayer');

  /// See `AppStrings.tournamentFreeEntry`.
  String get tournamentFreeEntry => lookUp('tournamentFreeEntry');

  /// See `AppStrings.tournamentFormatKnockout`.
  String get tournamentFormatKnockout => lookUp('tournamentFormatKnockout');

  /// See `AppStrings.tournamentRules`.
  String get tournamentRules => lookUp('tournamentRules');

  /// See `AppStrings.tournamentBracket`.
  String get tournamentBracket => lookUp('tournamentBracket');

  /// See `AppStrings.tournamentClosesIn`.
  String get tournamentClosesIn => lookUp('tournamentClosesIn');

  /// See `AppStrings.tournamentCheckInClosesIn`.
  String get tournamentCheckInClosesIn => lookUp('tournamentCheckInClosesIn');

  /// See `AppStrings.tournamentEnterWithin`.
  String get tournamentEnterWithin => lookUp('tournamentEnterWithin');

  /// See `AppStrings.tournamentRound`.
  String get tournamentRound => lookUp('tournamentRound');

  /// See `AppStrings.tournamentBye`.
  String get tournamentBye => lookUp('tournamentBye');

  /// See `AppStrings.tournamentWalkover`.
  String get tournamentWalkover => lookUp('tournamentWalkover');

  /// See `AppStrings.tournamentAwaiting`.
  String get tournamentAwaiting => lookUp('tournamentAwaiting');

  /// See `AppStrings.tournamentAlreadyIn`.
  String get tournamentAlreadyIn => lookUp('tournamentAlreadyIn');

  /// See `AppStrings.tournamentResults`.
  String get tournamentResults => lookUp('tournamentResults');

  /// See `AppStrings.tournamentCancelledBecause`.
  String get tournamentCancelledBecause => lookUp('tournamentCancelledBecause');

  /// See `AppStrings.tournamentJoiningOpensIn`.
  String get tournamentJoiningOpensIn => lookUp('tournamentJoiningOpensIn');

  /// See `AppStrings.tournamentStartsIn`.
  String get tournamentStartsIn => lookUp('tournamentStartsIn');

  /// See `AppStrings.tournamentCheckInOpen`.
  String get tournamentCheckInOpen => lookUp('tournamentCheckInOpen');

  /// See `AppStrings.tournamentCancelRegistration`.
  String get tournamentCancelRegistration => lookUp('tournamentCancelRegistration');

  /// See `AppStrings.tournamentWithdrawn`.
  String get tournamentWithdrawn => lookUp('tournamentWithdrawn');

  /// See `AppStrings.tournamentViewResult`.
  String get tournamentViewResult => lookUp('tournamentViewResult');

  /// See `AppStrings.tournamentFinished`.
  String get tournamentFinished => lookUp('tournamentFinished');

  /// See `AppStrings.tournamentCancelled`.
  String get tournamentCancelled => lookUp('tournamentCancelled');

  /// See `AppStrings.tournamentCancelledHint`.
  String get tournamentCancelledHint => lookUp('tournamentCancelledHint');
}
