import 'package:scribble_guess/core/errors/failure.dart';
import 'package:scribble_guess/core/utils/result.dart';
import 'package:scribble_guess/models/chat_message.dart';

/// Chat and guessing seam between the UI and whatever backend relays messages.
///
/// One channel carries plain chat, guesses and system notices, because the
/// server decides which a message is. A guess is never judged on the client:
/// [send] transmits the raw text, the server matches it against the secret
/// word and echoes back a [ChatMessage] already typed as
/// `ChatMessageType.correctGuess`, `closeGuess`, `guess` or `chat`.
///
/// Two secrecy rules follow. A correct guess is broadcast without its text so
/// onlookers cannot read the answer, and the server suppresses messages from
/// players who have already guessed correctly so they cannot leak the word to
/// the rest of the room. `GuessMatcher` exists for the practice-mode
/// implementation and for tests, never to shortcut the server.
///
/// No method throws. Failures are returned as [Err] carrying a [Failure].
abstract interface class ChatRepository {
  /// Chat, guess and system messages in arrival order.
  ///
  /// Includes the `ChatMessageType.system`, `playerJoined`, `playerLeft` and
  /// `hint` entries generated by the server. Implementations keep at most
  /// `AppConstants.chatHistoryLimit` messages and replay them to new
  /// listeners. Completes only on [dispose].
  Stream<ChatMessage> get messages;

  /// Sends [text] as chat or as a guess, whichever the server decides.
  ///
  /// [text] should be trimmed and no longer than
  /// `AppConstants.maxChatLength`; the server enforces the same bounds and
  /// rejects anything else. An [Ok] means the server accepted the message, and
  /// the echoed [ChatMessage] arrives on [messages] — never append the local
  /// text optimistically, or a suppressed guess would still show up on the
  /// sender's own device.
  ///
  /// Fails with [AppErrorCode.validation] for empty or over-long text,
  /// [AppErrorCode.invalidAction] when the sender is muted or is the current
  /// drawer, or a transport code.
  Future<Result<void>> send(String text);

  /// Releases subscriptions and closes [messages].
  ///
  /// Safe to call more than once; the instance is unusable afterwards.
  void dispose();
}
