// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClCRFf1h3jnOdocEnlAxY5DRiYNlKM_lg',
    appId: '1:669548706857:web:e34cacf182ddc7f51d3038',
    messagingSenderId: '669548706857',
    projectId: 'scribbleguess-33e76',
    authDomain: 'scribbleguess-33e76.firebaseapp.com',
    storageBucket: 'scribbleguess-33e76.firebasestorage.app',
    measurementId: 'G-0WZ3M1ZNLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6SESgxEDCBfqrqLU8T_GDNA7F4TW3vms',
    appId: '1:669548706857:android:817cc63ec35f4b3c1d3038',
    messagingSenderId: '669548706857',
    projectId: 'scribbleguess-33e76',
    storageBucket: 'scribbleguess-33e76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtvP6A8bpDpOO6qaskZr_6_GtOwmQqWQg',
    appId: '1:669548706857:ios:1b3f3e9c691102061d3038',
    messagingSenderId: '669548706857',
    projectId: 'scribbleguess-33e76',
    storageBucket: 'scribbleguess-33e76.firebasestorage.app',
    iosBundleId: 'com.scribbleguess.scribbleGuess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtvP6A8bpDpOO6qaskZr_6_GtOwmQqWQg',
    appId: '1:669548706857:ios:1b3f3e9c691102061d3038',
    messagingSenderId: '669548706857',
    projectId: 'scribbleguess-33e76',
    storageBucket: 'scribbleguess-33e76.firebasestorage.app',
    iosBundleId: 'com.scribbleguess.scribbleGuess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClCRFf1h3jnOdocEnlAxY5DRiYNlKM_lg',
    appId: '1:669548706857:web:364459f9b001419c1d3038',
    messagingSenderId: '669548706857',
    projectId: 'scribbleguess-33e76',
    authDomain: 'scribbleguess-33e76.firebaseapp.com',
    storageBucket: 'scribbleguess-33e76.firebasestorage.app',
    measurementId: 'G-GTMH2R6TCR',
  );
}
