// Regenerates the English catalogue and the typed accessors from
// lib/core/constants/app_strings.dart.
//
//   node tool/gen_i18n.js
//
// Run this after adding, renaming or removing an `AppStrings` member. The
// translated catalogues in lib/core/i18n/translations/ are hand-authored and
// are never touched by this script — a key they are missing simply falls back
// to English, which is why adding a string does not break any language.

const fs = require('fs');
const path = require('path');

const APP = process.argv[2] || path.join(__dirname, '..');
const src = fs.readFileSync(
  path.join(APP, 'lib/core/constants/app_strings.dart'),
  'utf8',
);

// Strip comment lines first, so prose in a doc comment cannot be mistaken for
// a declaration.
const code = src
  .split('\n')
  .filter((line) => !/^\s*\/\//.test(line))
  .join('\n');

const entries = [];
const re = /static const String (\w+)\s*=\s*([\s\S]*?);\s*\n/g;
let m;
while ((m = re.exec(code)) !== null) {
  const name = m[1];
  const raw = m[2];
  // app_strings.dart holds no escape sequences, so a plain literal match is
  // exact. Adjacent literals are concatenated the way Dart concatenates them.
  const parts = [];
  const lit = /'([^']*)'/g;
  let p;
  while ((p = lit.exec(raw)) !== null) parts.push(p[1]);
  if (parts.length === 0) {
    console.error('SKIP (no literal): ' + name);
    continue;
  }
  entries.push([name, parts.join('')]);
}

// The text between the quotes is emitted verbatim, deliberately: it is already
// valid Dart escape syntax, so re-escaping it would turn the `\n` in
// `locationNoticeBody` into a literal backslash-n and print it on screen.
const dartStr = (s) => "'" + s + "'";

const header =
  '// GENERATED by tool/gen_i18n.js from lib/core/constants/app_strings.dart.\n' +
  '// Do not edit by hand: run the generator instead.\n';

const enOut =
  header +
  '//\n' +
  '// The English catalogue. Every other language falls back to it key by key,\n' +
  '// so an untranslated entry renders in English rather than blank.\n' +
  '\n' +
  '/// English UI copy, keyed by `AppStrings` member name.\n' +
  'const Map<String, String> enStrings = <String, String>{\n' +
  entries.map((e) => '  ' + dartStr(e[0]) + ': ' + dartStr(e[1]) + ',').join('\n') +
  '\n};\n';

const gOut =
  header +
  '\n' +
  "part of 'app_text.dart';\n" +
  '\n' +
  '/// The generated accessors, one per `AppStrings` member.\n' +
  '///\n' +
  '/// Typed getters rather than a bare map lookup at the call site: a mistyped\n' +
  '/// key is then a compile error, instead of a string that silently renders as\n' +
  '/// its own key.\n' +
  'mixin GeneratedText {\n' +
  '  /// Resolves [key] in the active language, falling back to English.\n' +
  '  String lookUp(String key);\n' +
  '\n' +
  entries
    .map(
      (e) =>
        '  /// See `AppStrings.' +
        e[0] +
        '`.\n  String get ' +
        e[0] +
        ' => lookUp(' +
        dartStr(e[0]) +
        ');',
    )
    .join('\n\n') +
  '\n}\n';

fs.mkdirSync(path.join(APP, 'lib/core/i18n/translations'), { recursive: true });
fs.writeFileSync(path.join(APP, 'lib/core/i18n/translations/en.dart'), enOut);
fs.writeFileSync(path.join(APP, 'lib/core/i18n/app_text.g.dart'), gOut);

// A flat manifest, for authoring and reviewing the other catalogues.
if (process.argv[3]) {
  fs.writeFileSync(
    path.join(process.argv[3], 'strings.json'),
    JSON.stringify(Object.fromEntries(entries), null, 0),
  );
}

console.error('parsed ' + entries.length + ' entries; wrote en.dart and app_text.g.dart');
