import 'package:flutter/material.dart';
import 'package:scribble_guess/theme/app_colors.dart';

/// One editable source for every player-facing platform-brand value.
///
/// The distinction this class exists to protect: **STUPID GAMES is the
/// application, and Scribble & Guess is one of the games inside it.** Game
/// names belong in `GameDefinition` and stay stable; changing anything here
/// changes only the container application's identity, never a game's.
///
/// No screen should hardcode the app name. Read it from here, or — where the
/// string is shown to a player and a translation exists — from
/// `context.l10n.appName`.
@immutable
class AppBrandConfig {
  const AppBrandConfig({
    required this.appName,
    required this.shortName,
    required this.tagline,
    required this.blurb,
    required this.botLabel,
    required this.botLabelPlural,
    required this.logoAsset,
    required this.iconAsset,
    required this.primaryColor,
    required this.secondaryColor,
    required this.splashBackground,
    required this.supportEmail,
    required this.websiteUrl,
  });

  /// The name, as it is written everywhere: shouted, both words.
  final String appName;

  /// The name where a full one will not fit — a dense app bar, a share sheet.
  final String shortName;

  /// One line under the logo.
  final String tagline;

  /// The two-sentence pitch, for store listings and the about screen.
  final String blurb;

  /// What this platform calls a bot, in the singular.
  ///
  /// Held here rather than spelled out at call sites because it is a brand
  /// decision, not a gameplay one: the player is told they are playing with
  /// "a Stupid", and every screen has to say the same word or the joke reads
  /// as a bug. See `PLAY WITH STUPID` in the game selection.
  final String botLabel;

  /// The same, in the plural.
  final String botLabelPlural;

  /// Master logo artwork, regenerated by `tool/generate_brand_assets.dart`.
  ///
  /// Nothing in the app loads this at runtime — the logo is drawn live from
  /// `Brand` geometry. It is here so store listings and press have one
  /// canonical path, and as the hook for raster art if it ever replaces the
  /// vector mark.
  final String logoAsset;

  /// Master app-icon artwork, likewise regenerated rather than hand-exported.
  final String iconAsset;

  /// The platform's primary. Used for platform chrome only — a game's own
  /// colour comes from its `GameDefinition`.
  final Color primaryColor;

  /// The platform's secondary.
  final Color secondaryColor;

  /// What the splash screen is printed on.
  final Color splashBackground;

  /// Where "Report a problem" and "Contact support" send mail.
  final String supportEmail;

  /// The marketing site.
  final String websiteUrl;

  /// The live identity.
  static const AppBrandConfig current = AppBrandConfig(
    appName: 'STUPID GAMES',
    shortName: 'Stupid Games',
    tagline: 'Make stupid decisions. Together.',
    blurb:
        'A pile of ridiculous multiplayer mini-games where the worst possible '
        'decision is usually the funniest one. Bring friends, or bring Stupids.',
    botLabel: 'Stupid',
    botLabelPlural: 'Stupids',
    logoAsset: 'brand/mark_full_1024.png',
    iconAsset: 'brand/app_icon_1024.png',
    primaryColor: AppColors.brandViolet,
    secondaryColor: AppColors.brandOrange,
    splashBackground: AppColors.bg,
    supportEmail: 'support@stupidgames.app',
    websiteUrl: 'https://stupidgames.app',
  );
}
